### ISSUE TITLE
Slack channel link on FAQ.md not working

### ISSUE THREAD

**Issue by akarsh** [kallaway/100-days-of-code#105]
@Kallaway 
The slack channel link [https://tinyurl.com/y73urlup](https://tinyurl.com/y73urlup) not working.
Can you please update the link

**Comment by willoughbylabs** [comment]
Hello @akarsh, please try this link [https://goo.gl/xw4K75](https://goo.gl/xw4K75) to see if you are able to join from it! 
([source: 100 Days of Code website](http://www.100daysofcode.com/resources/))

**Comment by akarsh** [comment]
I added it in my pull request #106 ; I found the link on the website.
Thank you @willoughbylabs

**Comment by rishiip** [comment]
@akarsh @willoughbylabs Updated link also not working.

<img width="473" alt="screen shot 2018-10-01 at 12 35 18 pm" src="https://user-images.githubusercontent.com/7964257/46274474-3a9dcb80-c577-11e8-82e8-aeda24f1aa02.png">

**Comment by rishiip** [comment]
@akarsh @willoughbylabs I am using following invite link.

https://join.slack.com/t/100xcode/shared_invite/enQtNDA4MjgzMTY5MTA3LTEyMjBhYzMzYzM5NTFjZDU0MGMxZjA3Zjk5NTVjMTA1ZjRmNDNiMGNiNDIzMjg2Yjk4OTRhZGUwZmJjNDFmY2E

**Comment by Narshe1412** [comment]
@rishiip No longer working

**Comment by Narshe1412** [comment]
#184 is a better fix for this Issue
