### ISSUE TITLE
typo in the French resources page

### ISSUE THREAD

**Issue by SylvainJunca** [kallaway/100-days-of-code#144]
"disponble" should be "disponible"

**Comment by SylvainJunca** [comment]
proposed a correction

**Comment by kallaway** [comment]
Hi @SylvainJunca - can you submit this change as a Pull Request?

**Comment by SylvainJunca** [comment]
Done. :)

Sorry I didn't do it this way first. I clearly don't know how to use Github and didn't wanted to break something.
